#!/bin/sh
# switch.sh — Interactively switch the remapped app
# Usage: ./switch.sh [adb_target]

ADB="${ADB:-adb}"
TV="${1:-192.168.1.209:5555}"
CONF_PATH="/data/local/tmp/keyremap.conf"

echo "=== tv-keyremap: Switch App ==="
echo ""

# Connect
$ADB connect "$TV" >/dev/null 2>&1
if ! $ADB -s "$TV" shell echo ok >/dev/null 2>&1; then
  echo "ERROR: Cannot reach $TV"
  exit 1
fi

# Show current config
echo "Current config:"
CURRENT=$($ADB -s "$TV" shell cat "$CONF_PATH" 2>/dev/null | grep "^TARGET=" | sed 's/TARGET=//' | tr -d '"' | tr -d "'" | tr -d '\r')
if [ -n "$CURRENT" ]; then
  echo "  → $CURRENT"
else
  echo "  (not configured)"
fi
echo ""

# Get all launchable packages with friendly names
echo "Fetching installed apps..."
echo ""

APPS=$($ADB -s "$TV" shell "pm list packages -3 2>/dev/null" | sed 's/package://' | tr -d '\r' | sort)

i=1
for pkg in $APPS; do
  # Get app label
  LABEL=$($ADB -s "$TV" shell "dumpsys package $pkg" 2>/dev/null | grep -m1 "applicationInfo" | sed 's/.*ApplicationInfo{[^ ]* //' | sed 's/}.*//' | tr -d '\r')
  # Get launcher activity
  ACTIVITY=$($ADB -s "$TV" shell "dumpsys package $pkg" 2>/dev/null | grep -B5 "LEANBACK_LAUNCHER\|android.intent.category.LAUNCHER" | grep "$pkg/" | head -1 | sed "s/.*\($pkg\/[^ ]*\).*/\1/" | tr -d ' \r')
  if [ -z "$ACTIVITY" ]; then
    ACTIVITY=$($ADB -s "$TV" shell "cmd package resolve-activity --brief -c android.intent.category.LEANBACK_LAUNCHER $pkg 2>/dev/null" | tail -1 | tr -d '\r')
  fi
  [ -z "$ACTIVITY" ] && continue

  # Mark current
  MARK="  "
  case "$CURRENT" in
    *"$pkg"*) MARK="→ " ;;
  esac

  echo "${MARK}[$i] $pkg"
  echo "      $ACTIVITY"
  eval "APP_$i=$pkg"
  eval "ACT_$i=$ACTIVITY"
  i=$((i + 1))
done

# Also list system apps that might be useful
echo ""
echo "  [$i] (Enter a custom activity manually)"
eval "APP_$i=custom"
MAX=$i

echo ""
printf "Select app [1-$MAX]: "
read CHOICE

if [ -z "$CHOICE" ] || [ "$CHOICE" -lt 1 ] 2>/dev/null || [ "$CHOICE" -gt "$MAX" ] 2>/dev/null; then
  echo "Invalid choice."
  exit 1
fi

eval "SELECTED_PKG=\$APP_$CHOICE"
eval "SELECTED_ACT=\$ACT_$CHOICE"

if [ "$SELECTED_PKG" = "custom" ]; then
  printf "Enter activity (e.g. com.example.app/.MainActivity): "
  read SELECTED_ACT
  if [ -z "$SELECTED_ACT" ]; then
    echo "No activity provided."
    exit 1
  fi
fi

echo ""
echo "Selected: $SELECTED_ACT"

# Read existing config to preserve other settings
EXISTING_DEVICE=$($ADB -s "$TV" shell cat "$CONF_PATH" 2>/dev/null | grep "^DEVICE=" | tr -d '\r')
EXISTING_SCANCODE=$($ADB -s "$TV" shell cat "$CONF_PATH" 2>/dev/null | grep "^SCANCODE_LE=" | tr -d '\r')
EXISTING_COOLDOWN=$($ADB -s "$TV" shell cat "$CONF_PATH" 2>/dev/null | grep "^COOLDOWN=" | tr -d '\r')

# Write config
$ADB -s "$TV" shell "cat > $CONF_PATH << 'CONF'
# tv-keyremap config — auto-generated by switch.sh
${EXISTING_DEVICE:-DEVICE=/dev/input/event3}
${EXISTING_SCANCODE:-SCANCODE_LE=53050c00}
TARGET=$SELECTED_ACT
${EXISTING_COOLDOWN:-COOLDOWN=2}
CONF" 2>/dev/null

echo ""
echo "Config written to $CONF_PATH"

# Verify
VERIFY=$($ADB -s "$TV" shell cat "$CONF_PATH" 2>/dev/null | tr -d '\r')
echo "$VERIFY"

# Check if daemon is running
RUNNING=$($ADB -s "$TV" shell ps 2>/dev/null | grep "shell.*dd$" | tr -d '\r')
if [ -n "$RUNNING" ]; then
  echo ""
  echo "Daemon is running — it will pick up the new config on next button press."
else
  echo ""
  echo "Daemon is NOT running. Starting it..."
  $ADB -s "$TV" shell "rm -rf /data/local/tmp/keyremap.lock" >/dev/null 2>&1
  $ADB -s "$TV" shell "setsid sh /data/local/tmp/keyremap.sh < /dev/null > /dev/null 2>&1 &" </dev/null >/dev/null 2>&1
  sleep 3
  VERIFY_RUN=$($ADB -s "$TV" shell ps 2>/dev/null | grep "shell.*dd$" | tr -d '\r')
  if [ -n "$VERIFY_RUN" ]; then
    echo "Daemon started."
  else
    echo "Failed to start daemon."
    exit 1
  fi
fi

echo ""
echo "Done. Press the remapped button to test."
